spring.application.name=resume-analyzer
# Database Connection (To your Docker DB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.datasource.url=jdbc:postgresql://localhost:55454/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.ai.retry.autoconfigure.SpringAiRetryAutoConfiguration,\
org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration,\
org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.docker.compose.enabled=false
spring.main.allow-bean-definition-overriding=true
spring.ai.retry.enabled=false
spring.ai.openai.audio.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.audio.speech.enabled=false
# AI Config (Ollama)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1